### ISSUE TITLE
Build llvm failed

### ISSUE THREAD

**Issue by shao-hua-li** [DeadCodeProductions/ccbuilder#34]
After I specify `--cache-prefix` and `--repos-dir`, LLVM got built normally but failed to install. The error report said the error happened at https://github.com/DeadCodeProductions/ccbuilder/blob/9cd8c59dcf43dc902868d6ec371ded1bc283f698/ccbuilder/builder/builder.py#L297

I checked the cache-prefix dir, where the llvm dir got deleted somehow during installing.

**Comment by shao-hua-li** [comment]
Commit c82c62935be05a2ed17834a1f04faecaf13a7161 works fine. So I guess the problem is introduced by the recent commit.

**Comment by thetheodor** [comment]
https://github.com/DeadCodeProductions/ccbuilder/commit/20487b8ba600ca1a850f40baf323509e0b4ab856#r90615220

I think that's the issue. 

@Quarub
