### ISSUE TITLE
Question: The path to log file

### ISSUE THREAD

**Issue by shao-hua-li** [DeadCodeProductions/ccbuilder#35]
Hi,
Where can I find the log file? Expecially after I specify `--cache-prefix` and `--repos-dir`?

Thanks,
Shaohua

**Comment by Quarub** [comment]
Calling `ccbuilder`  from the CLI will not create a log file.
Older versions wrote it to `$CACHE_PREFIX/logs`. 

Do you want a flag to set the logging directory?

**Comment by shao-hua-li** [comment]
Thanks!
