### ISSUE TITLE
ccbuilder failed to build gcc 495079550e135c7ad0605e9c549202c35625cde7

### ISSUE THREAD

**Issue by shao-hua-li** [DeadCodeProductions/ccbuilder#50]
I tried ccbuilder==v0.1.1 to build gcc 495079550e135c7ad0605e9c549202c35625cde7, which failed me with message:
```
../../../../libsanitizer/sanitizer_common/sanitizer_internal_defs.h:339:72: error: narrowing conversion of ‘-1’ from ‘int’ to ‘long unsigned int’ [-Wnarrowing
```

I tried with CC=gcc-9/10/11, all failed.

**Comment by thetheodor** [comment]
Does it build outside ccbuilder?

**Comment by shao-hua-li** [comment]
Ah, it should be a GCC program. I tried with my own building script and it failed as well.
